### ISSUE TITLE
Даешь README!

### ISSUE THREAD

**Issue by LencoDigitexer** [EVGESHAd/vk-cpp-bot#3]
Может, стоит написать хотя бы базовую инструкцию?

**Comment by edombek** [comment]
Стоит. Руки никак не дойдут)

**Comment by LencoDigitexer** [comment]
Ну просто начни. Хотя бы технологии подключения опиши. Установка через make, make install?

**Comment by edombek** [comment]
> Ну просто начни. Хотя бы технологии подключения опиши. Установка через make, make install?

Не, собираешь make
запускаешь первый раз
в config.json прописываешь токен для группы, и для пользователя
у группы должен быть включен лонгпул версии 5.92

для доступа к всем функциям напиши боту чтонить после запуска, останови и в dat.json выставь себе права уровня 5, после чего снова запускай

**Comment by edombek** [comment]
Расписал.
